name: Test Install Script

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - test-install-script
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'install.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'install.sh'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, archlinux]
        include:
          - os: ubuntu-latest
            image: ubuntu:latest
          - os: ubuntu-22.04
            image: ubuntu:22.04
          - os: archlinux
            image: archlinux:latest

    name: ${{ matrix.os }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    env:
      DEBIAN_FRONTEND: noninteractive


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make install.sh Executable
        run: chmod +x install.sh
      
      - name: Arch Linux Specific Setup
        if: matrix.os == 'archlinux'
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm
          pacman -S --noconfirm sudo
        

      - name: Run Installation Script
        run: ./install.sh


  wsl:
    name: WSL
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up WSL2
        uses: vampire/setup-wsl@v6

      - name: Make Executable and Run Script
        run: |
          wsl bash -c "
          cd \$(wslpath '${{ github.workspace }}') &&
          chmod +x install.sh &&
          ./install.sh
          "
  macos:
    name: MacOS Latest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make install.sh Executable
        run: chmod +x install.sh

      - name: Run Installation Script
        run: ./install.sh
